### ISSUE TITLE
Test MVR in a Move manifest

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-names#32]

**Comment by DaughterOfMars** [comment]
In order to resolve mvr names you must add both:

```toml
[dependencies]
core = { r.mvr = "@mvr/core" }
```

and 

```toml
[r.mvr]
network = "mainnet"
```

# Notes

- I do not know the reason for the `r.` and you cannot change it arbitrarily. 
- The core lib is not available on testnet which is problematic if you are developing as you can only build the package for the mainnet.
- The `mvr` binary must be installed in order to resolve these dependencies.
